/**
 * 日程页私有文案。
 */
export const TEXT = {
  schedule: {
    subtitle: '为智能体设置定时或一次性的计划任务',
    calendar: '日历',
    list: '列表',
    createSchedule: {
      title: '创建日程',
      description: '为智能体设置定时或一次性的计划任务。',
      descriptionLabel: '描述',
      descriptionPlaceholder: '描述这个计划任务的用途...',
      namePlaceholder: '例如：每日报告',
    },
    deleteSchedule: { entity: '日程' },
    endAt: '结束日期',
    end_at: '结束时间',
    executionHistory: '执行历史',
    freqDaily: '每天',
    freqMonthly: '每月',
    freqOnce: '一次',
    freqWeekly: '每周',
    frequency: '频率',
    friday: '周五',
    more: '更多',
    monday: '周一',
    nextMonth: '下个月',
    nextYear: '下一年',
    noSchedules: '暂无日程',
    noSchedulesDescription: '创建日程以自动化智能体任务。',
    pickDate: '选择日期',
    permissionMode: '权限模式',
    timezone: '时区',
    triggerTime: '触发时间',
    createdAt: '创建时间',
    dayOfMonthSuffix: '日',
    stateful: '有状态',
    statefulDesc: '开启后，每次触发复用同一个会话以累积上下文；关闭则每次触发都创建新会话。',
    previousMonth: '上个月',
    previousYear: '上一年',
    saturday: '周六',
    sunday: '周日',
    thursday: '周四',
    today: '今天',
    tuesday: '周二',
    wednesday: '周三',
  },
};
